### ISSUE TITLE
Set "develop" branch as default instead of "master" branch

### ISSUE THREAD

**Issue by makenowjust** [NozeIO/Noze.io#11]
Now `master` branch is default, so for the first time we saw a tree not updated while a month, we were afraid: "is this project alive?"

But `develop` branch is living surely. I think it is better.

**Comment by helje5** [comment]
Well, the `master` branch is what interested people should play with. `develop` is potentially unstable and may not always compile cleanly.

Anyways, I made a new release with the few changes in `develop`.

Summary: Lets stick to `master` as the primary branch but try to make at least a monthly release ;->

**Comment by makenowjust** [comment]
Thanks @helje5!
