### ISSUE TITLE
_ArrayType and Swift 3

### ISSUE THREAD

**Issue by mrhevor** [NozeIO/Noze.io#2]
As object _ArrayType doesn't exist in Swift 3

**Comment by helje5** [comment]
You are on the `develop` branch? `master` is Swift 2.x and Swift 3preview4. `develop` is being updated for 3.0.

**Comment by helje5** [comment]
`develop` builds fine against Swift 3.0. Will do a release to `master` once the Linux port works.

**Comment by mrhevor** [comment]
Great work!
